### ISSUE TITLE
Why is (x, 0) the commitment vertex? why not sign all (x,y)?

### ISSUE THREAD

**Issue by Nuhvi** [AljoschaMeyer/reed#1]
I hope you don't mind me moving the conversation here for the benefit of everyone.

Earlier I asked about the proof (certificate) that links entry **14** to a more recent signature at **27**, and you commented:

> the commitment vertex for 27 is (27, 0), so you'd trace the path from that to (14, 0) (yellow in the image). The certificate then consists of the blue vertices. Ignore the magenta =S

![link-from-27-to-14](https://github.com/AljoschaMeyer/reed/assets/40009100/972cf28b-4c5b-4767-8755-f22685eda18b)

Which is unfortunate, because that is more than what a ternary Merkle tree would require to proof connection between the most recent signed root (27,3) and (14) 

<img width="1298" alt="ternary-merkle-tree-proof" src="https://github.com/AljoschaMeyer/reed/assets/40009100/1c854b65-6b19-43a6-bea2-1e305fdae546">

But, now I am wondering... why? why can't I sign all vertices including (27,3) in Reed, so the certificate is the same as a ternary merkle tree? In fact, why sign (27, 0) when signing (27, 3) is enough?

<img width="1342" alt="Reed-certificate-27-14" src="https://github.com/AljoschaMeyer/reed/assets/40009100/31610db2-5789-4b33-9740-8a3c7dacda7b">

**Comment by Nuhvi** [comment]
Somewhat answering my own question... at least for my usecase;

Consider a trusted single-writer (i.e not a transparency log) creating an append-only B-tree, they can sign each **(x, 0)** commit, and each reader only needs to trust each entry with its stand-alone signature over the **(x, 0)** commitment, that is probably the ideal situation especially because the writer can drop old snapshots of the tree, and gc orphaned entries, in fact, if not for the next scenario, a `timestamp` (or cheaper: `seq` varU64) should suffice.

<img width="1342" alt="before-key-rotation" src="https://github.com/AljoschaMeyer/reed/assets/40009100/6fe11201-87d9-46eb-ba37-d976c561b2c9">

The reason to still use Reed then, is when a key rotation occurs, now the same "log" is going to be signed by a new key going forward (after the red stroke), and there is a short opportunity for someone who downloaded **(14)** with its standalone signature, to download  **(13,0), (15), (12,1), (18,0), and (9,2)** to link **(14)** to **(19)** (the first signed entry by the _current_ signer).

<img width="1342" alt="Reed-certificate-19-14" src="https://github.com/AljoschaMeyer/reed/assets/40009100/e62c6a4a-4e0f-43a2-8b9b-4eecd52e87b2">

So maybe I should think about Reed as a hybrid between Willow and Merkle trees (for single writers);
1. On one hand, it offers the flexibility of sharing standalone signatures (as long as signer keys are not rotated yet).
2. On the other hand, entries signed with older keys can be "linked" to the nearest entry with a "current" signature.
3. Moreover, if entries are contiguous enough (you downloaded **19-27**) you have the _option_ to drop signatures (except the last), and replace them with "link" hashes, which can be calculated on demand instead of stored on disk.

**Comment by AljoschaMeyer** [comment]
> why can't I sign all vertices including (27,3) in Reed, so the certificate is the same as a ternary merkle tree? In fact, why sign (27, 0) when signing (27, 3) is enough?

In general, you can sign whatever you want, that sits outside the jurisdiction of Reed. Chances are, for example, that your events include some sort of signature as well. The example at the end of the spec merely recommends a way of using Reed as a transparency log.

**Comment by Nuhvi** [comment]
I think signing (x, 0) has the advantage I mentioned in (#3) in my last comment; where you can drop most signatures of contiguous events and use their merkle structure. 

Not sure if that is desirable though since you might want to revert to standalone proofs (proof for one event).

However, unlike Hypercore or even MST (MST is worse), the overhead (extra data other than the event and the signature) of "standalone" proofs is tiny:
Hypercore => log(n) * 32 bytes
MST           => logb(n) * b  (including the keys in the page)
Reed          => 32 bytes (backlink? jumplink?)

Am I correct here?

**Comment by AljoschaMeyer** [comment]
Jup. In the [general paper](https://aljoscha-meyer.de/reed/assets/references/meyer2023sok.pdf), I call this the *identifier size*. The table on page 13 lists amortized and worst-case sizes, and those for hypercore are indeed logarithmic in the worst case. Linking schemes (like the old bamboo one, or the reed one) have a constant worst-case identifier size.

**Comment by Nuhvi** [comment]
And in Reed that constant is smaller than in Bamboo too. Great.
