### ISSUE TITLE
Can I drop all labels from lower level on every entry?

### ISSUE THREAD

**Issue by Nuhvi** [AljoschaMeyer/reed#2]
Trying to figure out a rule for GC'ing labels that I already have their entry, while creating new entries cheaply.

Is it accurate to say, on each label with hight Y I can delete all labels with height Y-1?

For example:
- (3,0) => Nothing to delete
- (3,1) => Delete (1,0), (2,0), (3,0)
- (6,1) => Delete (4,0), (5,0), (6,0)
- (9,1) => Delete (7,0), (8,0), (9,0)
- (9,2) => Delete (3,1), (6,1), (9,1)

At least it appears so from all the graphs, just want to check the math.

**Comment by AljoschaMeyer** [comment]
To be able to continue creating new events and compute the labels of all their associated vertices, you need to keep around the labels of the vertices of the shortest path from the most recent event `x` to the [topmost vertex](https://aljoscha-meyer.de/reed/#topmost) of the greatest power of three that is strictly less than or equal to `x`.

In the papers, this is the information needed to be able to continue to call `iterative_digest` ([https://aljoscha-meyer.de/reed/assets/references/meyer2023sok.pdf](https://aljoscha-meyer.de/reed/assets/references/meyer2023sok.pdf), section 4).

**Comment by Nuhvi** [comment]
Thanks, I will try to see if my rule of thumb satisfies that formal definition for larger sequences than in the paper. It would be nice if it does, since it is simpler to check and implement: check the top of the stack, if its y is smaller than the new vertex, delete it and repeat until it is not true, then push the new vertex.
